import { Product } from './types';

export const CATEGORIES = [
  { id: 'all', name: 'Tất cả nông sản', icon: 'Sparkles' },
  { id: 'vegetables', name: 'Rau củ tươi', icon: 'Leaf' },
  { id: 'fruits', name: 'Trái cây đặc sản', icon: 'Apple' },
  { id: 'grains', name: 'Gạo & Ngũ cốc', icon: 'Wheat' },
  { id: 'spices', name: 'Gia vị & Thảo mộc', icon: 'Flame' },
  { id: 'other', name: 'Nông sản khác', icon: 'Grid' },
];

export const LOCATIONS = [
  'Đà Lạt, Lâm Đồng',
  'Bắc Giang',
  'Sơn La',
  'Đồng Tháp',
  'Bến Tre',
  'Cần Thơ',
  'Đắk Lắk',
  'Hải Dương',
  'Hưng Yên',
  'Thanh Hóa',
  'Nghệ An',
  'Quảng Nam',
  'Khánh Hòa',
  'Ninh Thuận',
];

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: 'sample_1',
    farmerId: 'farmer_bacgiang_1',
    farmerName: 'Nguyễn Văn Hùng (Hợp tác xã Lục Ngạn)',
    name: 'Vải thiều Lục Ngạn chính hiệu',
    category: 'Trái cây đặc sản',
    description: 'Vải thiều Lục Ngạn quả to tròn, vỏ đỏ rực, cùi dày hạt nhỏ, vị ngọt đậm đà, thu hoạch trực tiếp tại vườn buổi sáng sớm, đóng thùng xốp đá bảo quản tươi ngon.',
    price: 35000,
    unit: 'kg',
    quantity: 500,
    harvestDate: '2026-06-29',
    location: 'Bắc Giang',
    isOrganic: true,
    imageUrl: 'https://images.unsplash.com/photo-1628155930542-3c7a64e2c833?auto=format&fit=crop&q=80&w=800',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sample_2',
    farmerId: 'farmer_dalat_1',
    farmerName: 'Chị Mai (Nông trại Organic Đà Lạt)',
    name: 'Xà lách thủy canh Mỹ',
    category: 'Rau củ tươi',
    description: 'Xà lách Mỹ giòn ngọt, trồng theo phương pháp thủy canh tuần hoàn khép kín tiêu chuẩn VietGAP, cực kỳ sạch và nhiều dưỡng chất, thu hoạch đóng gói nguyên gốc rễ để giữ tươi lâu.',
    price: 28000,
    unit: 'bó (500g)',
    quantity: 120,
    harvestDate: '2026-06-30',
    location: 'Đà Lạt, Lâm Đồng',
    isOrganic: true,
    imageUrl: 'https://images.unsplash.com/photo-1556801712-76c8eb07bbc9?auto=format&fit=crop&q=80&w=800',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sample_3',
    farmerId: 'farmer_bentre_1',
    farmerName: 'Chú Ba Đất Chín Rồng',
    name: 'Dừa xiêm xanh lùn Bến Tre',
    category: 'Trái cây đặc sản',
    description: 'Dừa xiêm xanh chính gốc Bến Tre nước cực kỳ ngọt thanh, nhiều nước, giải nhiệt tuyệt vời ngày hè. Trái dừa còn nguyên buồng hoặc gọt vỏ sạch sẽ tiện dụng.',
    price: 15000,
    unit: 'trái',
    quantity: 300,
    harvestDate: '2026-06-28',
    location: 'Bến Tre',
    isOrganic: false,
    imageUrl: 'https://images.unsplash.com/photo-1563589173-0f7e1b73099c?auto=format&fit=crop&q=80&w=800',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sample_4',
    farmerId: 'farmer_dongthap_1',
    farmerName: 'Hợp tác xã Sen Tháp Mười',
    name: 'Hạt sen tươi bóc vỏ lấy tim',
    category: 'Rau củ tươi',
    description: 'Hạt sen tươi nguyên chất tự nhiên từ vùng trũng Đồng Tháp Mười, hạt to đều, đã được bóc sạch vỏ lụa và rút tim sen đắng, dùng nấu chè dưỡng nhan hay hầm gà bổ dưỡng, thanh mát.',
    price: 120000,
    unit: 'kg',
    quantity: 80,
    harvestDate: '2026-06-29',
    location: 'Đồng Tháp',
    isOrganic: true,
    imageUrl: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=800',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sample_5',
    farmerId: 'farmer_daklak_1',
    farmerName: 'A Sáng (Nông hộ Buôn Ma Thuột)',
    name: 'Cà phê Robusta mộc nguyên chất',
    category: 'Nông sản khác',
    description: 'Hạt cà phê Robusta chín đỏ chọn lọc bằng tay từ độ cao 800m tại Đắk Lắk, rang mộc vừa phải, mùi thơm nồng nàn quyến rũ, vị đắng đậm đà đúng chất Tây Nguyên.',
    price: 180000,
    unit: 'gói (500g)',
    quantity: 150,
    harvestDate: '2026-06-15',
    location: 'Đắk Lắk',
    isOrganic: true,
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sample_6',
    farmerId: 'farmer_sonla_1',
    farmerName: 'Chị Mùa (HTX Mộc Châu)',
    name: 'Mận hậu chín sẫm Mộc Châu',
    category: 'Trái cây đặc sản',
    description: 'Mận hậu Mộc Châu chín rộ giòn giòn, vị chua ngọt hài hòa mọng nước, vỏ ngoài có lớp phấn mỏng tự nhiên, thích hợp ăn tươi chấm muối ớt Tây Bắc hoặc ngâm siro mát lành.',
    price: 45000,
    unit: 'kg',
    quantity: 250,
    harvestDate: '2026-06-29',
    location: 'Sơn La',
    isOrganic: false,
    imageUrl: 'https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?auto=format&fit=crop&q=80&w=800',
    createdAt: new Date().toISOString(),
  }
];
